---
title: "SMOKERS"
author: "Enrique Olvera Monroy"
date: "2023-11-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#install.packages("AER")
#install.packages("ROSE")
```

```{r}
#CARGA DE LIBRERIAS
library(dplyr)
library(e1071)
library(ggplot2)
library(ISLR)
library(caret)
library(randomForest)
library(AER)
library(readr)
library(rpart)
library(xgboost)
library(ROSE)
library(kknn)
```



```{r}
#CARGA DE DATOS
dataset <- read.csv("Smokers.csv")
View(dataset)
```

```{r}
#CONCLUSIÓN:
# Sí hay que eliminar los outlayers de algunos valores, no tanto porque los valores no sean posibles, ya que algunos se, pueden disparar con en condiciones especiales, pero en algunos hay incongruencias, como en valores ALT y GTP. O errores de medición como en el caso de LDL. 

# Eyesight (Visión) - Izquierda y Derecha:
#   Descripción: Mide la agudeza visual en el ojo izquierdo y derecho.
#   Valores normales: 20/20 se considera visión normal. (del 0 al 2 en el dataframe, en el origen de los datos 0 es agudeza visual y 9.9 ceguera, los datos sólo contienen 0, 1 y 2)
#   Relación con el tabaco: Fumar puede aumentar el riesgo de enfermedades oculares como la degeneración macular y cataratas.
#
# Hearing (Audición) - Izquierda y Derecha:
# Descripción: Evalúa la capacidad auditiva en el oído izquierdo y derecho.
#   Valores normales: 1 es escuchar bien, 2 es escucha mal(anomalía)
#   Relación con el tabaco: Fumar puede aumentar el riesgo de pérdida de audición relacionada con la edad.
#   
# Systolic Blood Pressure (Presión Arterial Sistólica):
# Descripción: La presión arterial durante la fase de contracción del corazón.
#   Valores normales: Menos de 120 mm Hg.
#   Valores de riesgo: 120-139 mm Hg se considera prehipertensión.Más ya es hipertensión
#   Relación con el tabaco: Fumar puede aumentar temporalmente la presión arterial.
#   
# Relaxation Blood Pressure (Presión Arterial Diastólica):
# Descripción: La presión arterial durante la fase de relajación del corazón.
#   Valores normales: Menos de 80 mm Hg.
#   Valores de riesgo: 80-89 mm Hg se considera prehipertensión. más ya es hipertensión.
#   Relación con el tabaco: Fumar puede aumentar temporalmente la presión arterial.
#   
# Fasting Blood Sugar (Glucosa en Ayunas):
# Descripción: Nivel de glucosa en sangre después de un ayuno nocturno.
#   Valores normales: Menos de 100 mg/dL.
#   Valores de riesgo: 100-125 mg/dL se considera prediabetes.
#   Relación con el tabaco: Fumar puede aumentar el riesgo de resistencia a la insulina y diabetes tipo 2.
#   
# Cholesterol Total:
# Descripción: Cantidad total de colesterol en la sangre.
#   Valores normales: Menos de 200 mg/dL.
#   Valores de riesgo: 200-239 mg/dL se considera límite alto.
#   Relación con el tabaco: Fumar puede reducir los niveles de lipoproteínas de alta densidad (HDL) y aumentar el riesgo de enfermedad cardiovascular.
# 
# Triglyceride (Triglicéridos):
# Descripción: Tipo de grasa en la sangre.
#   Valores normales: Menos de 150 mg/dL.
#   Valores de riesgo: 150-199 mg/dL se considera límite alto.
#   Relación con el tabaco: Fumar puede aumentar los niveles de triglicéridos.
#   
# HDL Cholesterol (Colesterol HDL):
# Descripción: Conocido como "colesterol bueno", transporta el colesterol lejos de las células y los órganos.
#   Valores normales: Más de 60 mg/dL.
#   Valores de riesgo: Menos de 40 mg/dL se considera bajo.
#   Relación con el tabaco: Fumar puede reducir los niveles de HDL.
#   
# LDL Cholesterol (Colesterol LDL):
# Descripción: Conocido como "colesterol malo", se acumula en las paredes de los vasos sanguíneos.
#   Valores normales: Menos de 130 mg/dL.
#   Valores de riesgo: arriba de 175 mg/dL.
#   Relación con el tabaco: Fumar puede aumentar los niveles de LDL.
#   
# Hemoglobin (Hemoglobina):
# Descripción: Proteína en los glóbulos rojos que transporta oxígeno.
#   Valores normales: Varían según la edad y el género.
    # Hombres adultos: 13.8 a 17.2 gramos por decilitro (g/dL).
    # Mujeres adultas: 12.1 a 15.1 g/dL.
#   Relación con el tabaco: Fumar puede afectar la capacidad de la sangre para transportar oxígeno.
# 
# Urine Protein (Proteína en la Orina):
# Descripción: Mide la cantidad de proteína presente en la orina.
#   Valores normales: Los valores normales de proteína en la orina suelen ser inferiores a 150 miligramos por día. Niveles más altos pueden indicar problemas renales o enfermedades como la diabetes o la hipertensión. (el dataset mide del 1 al 6, 1 es baja, 2 es normal, y a partir del 3 aumenta.
#   Relación con el tabaco: Fumar puede contribuir a enfermedades renales.
# 
# Serum Creatinine (Creatinina en Suero):
# Descripción: Mide la función renal.
#   Valores normales: Varían según la edad y el género.
    # Adultos (18-60 años):
    # Hombres:
    # Normal: 0.6 a 1.2 miligramos por decilitro (mg/dL)
    # Mujeres:
    # Normal: 0.5 a 1.1 mg/dL
    # Adultos mayores (>60 años):
    # Hombres:
    # Normal: 0.7 a 1.3 mg/dL
    # Mujeres:
    # Normal: 0.6 a 1.2 mg/dL (en el dataset marca como normal .8 a 1.7mg/dL)
#   Relación con el tabaco: Fumar puede afectar la función renal.
# 
# AST (Aspartato Aminotransferasa) y ALT (Alanina Aminotransferasa):
# Descripción: Enzimas hepáticas que indican la salud del hígado.
#   Valores normales: Varían, pero valores elevados pueden indicar daño hepático.
    # Los valores normales pueden variar según el laboratorio y las unidades de medida, pero en general, los valores típicos pueden ser:
    # AST: 10 a 40 unidades por litro (U/L)
    # ALT: 7 a 56 U/L
#   Relación con el tabaco: Fumar puede contribuir al daño hepático.
#   
# GTP (γ-GTP):
# Descripción: Otra enzima hepática que puede indicar daño en el hígado.
#   Valores normales: Varían, pero valores elevados pueden indicar daño hepático.Los valores normales pueden variar, pero típicamente se encuentran en el rango de 9 a 48 U/L.
#   Relación con el tabaco: Fumar puede contribuir al daño hepático.
# 
# Dental Caries (Caries Dentales):
# Descripción: Presencia de cavidades en los dientes.
#   Valores normales: Dientes sanos sin cavidades.El dataset indica con 1 a quien sí tiene carios y con 0 a quien no tiene caries
#   Relación con el tabaco: Fumar puede aumentar el riesgo de enfermedades periodontales y caries.
```


```{r}
# TEMP CELDA DE PRUEBAS
# df de pruebas 
smokers_2 <- dataset

# variables derivadas (calculadas a partir de nuestros índices)
smokers_2$lipid_ratio <- (smokers_2$HDL + smokers_2$LDL) / smokers_2$Cholesterol
  # Rango Normal: 0.2 a 0.7
  # Bajo: Menos de 0.2
  # Elevado: Más de 0.7

smokers_2$lipid_ratio2 <- smokers_2$triglyceride / smokers_2$HDL
  # Rango Normal: 0.1 a 0.5
  # Bajo: Menos de 0.1
  # Elevado: Más de 0.5

smokers_2$systolic_relaxation_ratio <- smokers_2$systolic / smokers_2$relaxation
  # Rango Normal: 1 a 2
  # Bajo: Menos de 1
  # Elevado: Más de 2

#eliminado el índice renal por falta de info en el dataframe

# Definir rangos normales para cada variable (la mayoría sacados directo del origen del DF)
normal_ranges <- data.frame(
  variable = c("waist.cm.", "systolic", "relaxation", "fasting.blood.sugar", "Cholesterol", "triglyceride", "HDL", "LDL", "hemoglobin", "serum.creatinine", "AST", "ALT", "Gtp", "lipid_ratio", "lipid_ratio2", "systolic_relaxation_ratio"),
  normal_range = c("70-90", "90-120", "60-80", "70-100", "150-250", "30-150", "30-65", "0-130", "12-16", "0.5-1.2", "10-40", "7-56", "10-40", "0.2-1.5", "0-10", "0.5-2")
)

# Convertir el rango normal a un rango numérico
normal_ranges$normal_range <- t(apply(read.table(text = normal_ranges$normal_range, sep = "-"), 1, function(x) as.numeric(x)))

# Función para verificar si un valor está dentro del rango normal
is_within_normal_range <- function(value, normal_range) {
  return(value >= normal_range[1] & value <= normal_range[2])
}

# Verificar cada variable y marcar los valores fuera de rango
for (i in 1:nrow(normal_ranges)) {
  variable_name <- normal_ranges$variable[i]
  normal_range <- normal_ranges$normal_range[i, ]
  
  # Crear una nueva columna que indique si el valor está dentro del rango normal
  smokers_2$within_normal_range <- is_within_normal_range(smokers_2[[variable_name]], normal_range)
  
  # Imprimir el recuento de valores fuera del rango normal para cada variable
  cat("Valores fuera del rango normal para", variable_name, ":", sum(!smokers_2$within_normal_range), "\n")
}

# Quitar la columna temporal 'within_normal_range' después de la verificación
smokers_2$within_normal_range <- NULL

View(smokers_2)

# FILTROS ACTUALIZADOS
# Crear DataFrame para almacenar las filas filtradas
smokers_filtrados <- dataset

# Filtrar por valores muy elevados (raza ya a punto de colgar los tenis 9:)
smokers_filtrados <- smokers_filtrados[smokers_filtrados$waist.cm. <= 90, ]
smokers_filtrados <- smokers_filtrados[smokers_filtrados$systolic <= 160, ]
smokers_filtrados <- smokers_filtrados[smokers_filtrados$relaxation <= 100, ]
smokers_filtrados <- smokers_filtrados[smokers_filtrados$fasting.blood.sugar <= 200, ]
smokers_filtrados <- smokers_filtrados[smokers_filtrados$Cholesterol <= 300, ]
smokers_filtrados <- smokers_filtrados[smokers_filtrados$triglyceride <= 500, ]
smokers_filtrados <- smokers_filtrados[smokers_filtrados$HDL >= 30, ]
smokers_filtrados <- smokers_filtrados[smokers_filtrados$LDL <= 190, ]
smokers_filtrados <- smokers_filtrados[smokers_filtrados$hemoglobin <= 18, ]
smokers_filtrados <- smokers_filtrados[smokers_filtrados$Urine.protein < 4, ]
smokers_filtrados <- smokers_filtrados[smokers_filtrados$serum.creatinine <= 2.5, ]
smokers_filtrados <- smokers_filtrados[smokers_filtrados$AST <= 80, ]
smokers_filtrados <- smokers_filtrados[smokers_filtrados$ALT <= 100, ]
smokers_filtrados <- smokers_filtrados[smokers_filtrados$Gtp <= 60, ]

# Mostrar el resumen del DataFrame filtrado
View(smokers_filtrados)


```



```{r}
#EXPLORACIÓN DE LA ESTRUCTURA DEL DATASET
str(dataset)

```
Como podemos observar, el conjunto de datos tiene 159256 observaciones y 24 variables. Es un dataset sobre el historial médico de fumadores y no fumadores.

```{r}
dim(dataset)
```
```{r}
nombres_columnas <- colnames(dataset)
print(nombres_columnas)
```


```{r}
#INDICE DE MASA CORPORAL

# Calcular el índice de masa corporal (IMC) y agregarlo como una nueva columna
dataset$BMI <- dataset$"weight.kg." / ((dataset$"height.cm." / 100)^2)


```



```{r}
#ELIMINAR COLUMNA ID (VARIABLE CATEGÓRICA)

dataset <- subset(dataset, select = -c(id,  X, X.1,height.cm.,weight.kg.))


```


```{r}
#VISUALIZACIÓN DEL DATASET
head(dataset)

```

```{r}
#VISUALIZACIÓN DEL DATASET
tail(dataset)
```



```{r}
#CORRECCIÓN DE TIPOS DE DATOS

dataset$smoking <- as.logical(dataset$smoking)
dataset$dental.caries <- as.logical(dataset$dental.caries)


```



```{r}
#RESUMEN ESTADÍSTICO

summary(dataset)

```

```{r}
#VALORES NA

sum(is.na(dataset))

```

```{r}

#VALORES ÚNICOS

count(unique(dataset))

```

```{r}
#ESTADÍSTICAS POR COLUMNA

estadisticos <- sapply(dataset, function(col) {
  c(
    Promedio = mean(col),
    Mediana = median(col),
    Min = min(col),
    Max = max(col),
    Varianza = var(col),
    Desviacion_Estándar = sd(col)
  )
})

print(estadisticos)

```



```{r}
#IDENTIFICAR OUTLIERS

par(mfrow=c(1, 1))
boxplot(dataset, col = "lightblue", border = "black")
par(cex.axis=0.8) 
par(las=2)

```

```{r}

#BOXPLOT DE CADA COLUMNA

par(mfrow=c(2, 2))  # Cambia el número de filas y columnas de gráficos

for (col in colnames(dataset)) {
  boxplot(dataset[[col]], main = col, col = "lightblue", border = "black")
}

```


```{r}
#HISTOGRAMA DE CADA COLUMNA

par(mfrow=c(2, 2))  # Cambia el número de filas y columnas de gráficos

num_columnas <- ncol(dataset)

for (i in 1:(num_columnas - 3)) {
  col <- colnames(dataset)[i]
  hist(dataset[[col]], main = col, xlab = col, col = "lightblue", border = "black")
}

```


```{r}
#MATRIZ DE CORRELACIÓN ENTRE VARIABLES

matriz_correlacion <- cor(dataset)

#MAPA DE CALOR
library(corrplot)  
corrplot(matriz_correlacion, method = "color")
```
```{r}

#FILTRADO POR MEDICIONES ERRÓNEAS






```



```{r}

#ELIMINAR OUTLIERS DE TODAS LAS COLUMNAS


# Función para identificar y eliminar outliers
eliminar_outliers <- function(data, cols) {
  data_filtrado <- data
  
  for (col in cols) {
    # Calcula los límites superior e inferior
    Q1 <- quantile(data_filtrado[[col]], 0.25)
    Q3 <- quantile(data_filtrado[[col]], 0.75)
    IQR <- Q3 - Q1
    limite_inferior <- Q1 - 1.5 * IQR
    limite_superior <- Q3 + 1.5 * IQR
    
    # Filtra los datos para excluir los outliers
    data_filtrado <- data_filtrado %>% filter(data_filtrado[[col]] >= limite_inferior & data_filtrado[[col]] <= limite_superior)
  }
  
  return(data_filtrado)
}

# Especifica las columnas a las que deseas aplicar la eliminación de outliers
columnas_a_filtrar <- colnames(dataset)

# Aplica la función para eliminar outliers
dataset_filtrado <- eliminar_outliers(dataset, columnas_a_filtrar)

```


```{r}
#DATASET FILTRADO

par(mfrow=c(1, 1))
boxplot(dataset_filtrado, col = "lightblue", border = "black")
par(cex.axis=0.8) 
par(las=2)
```


```{r}
#ESTADÍSTICAS POR COLUMNA DATOS FILTRADOS

estadisticos_filtrado <- sapply(dataset_filtrado, function(col) {
  c(
    Promedio = mean(col),
    Mediana = median(col),
    Min = min(col),
    Max = max(col),
    Varianza = var(col),
    Desviacion_Estándar = sd(col)
  )
})

print(estadisticos_filtrado)

```


```{r}
#DATOS FILTRADOS

head(dataset_filtrado)
```



```{r}
#DIMENSIONES  DEL DATASET FILTRADO

dim(dataset_filtrado)

```

```{r}

#BOXPLOT DE CADA COLUMNA DEL DATASET FILTRADO

par(mfrow=c(2, 2))  # Cambia el número de filas y columnas de gráficos

for (col in colnames(dataset_filtrado)) {
  boxplot(dataset_filtrado[[col]], main = col, col = "lightblue", border = "black")
}

```
```{r}
#VARIABLE OBJETIVO COMO FACTOR
dataset_filtrado$smoking <- as.factor(dataset_filtrado$smoking)
```

```{r}
#CONTEO DE VALORES SMOKING (NO FUMADORES / FUMADORES)

summary(dataset_filtrado$smoking)
```


```{r}
dataset_filtrado
```


```{r}
#ESTANDARIZACIÓN DE DATOS 

# Reescalamos las variables para que tengan media cero y desviación estandar igual a 1


# Seleccionar todas las columnas excepto 'dental.caries' y 'smoking'
columnas_a_mutar <- setdiff(names(dataset_filtrado), c('dental.caries', 'smoking', 'hearing.left.','hearing.right.','Urine.protein'))

# Aplicar la función scale a las columnas seleccionadas
dataset_filtrado <- dataset_filtrado %>%
  mutate_at(vars(columnas_a_mutar), scale)

# Mostrar el conjunto de datos resultante
print(dataset_filtrado)
```


```{r}
#DIVIDIR DATOS DE ENTRENAMIENTO Y DE PRUEBA

set.seed(2023)

proporcion_entrenamiento <- 0.8
indice_particion <- createDataPartition(dataset_filtrado$smoking, p = proporcion_entrenamiento, list = FALSE)

datos_entrenamiento <- dataset_filtrado[indice_particion, ]
datos_prueba <- dataset_filtrado[-indice_particion, ]


```




```{r}
#DATOS DE ENTRENAMIENTO Y PRUEBA

dim(datos_entrenamiento)
dim(datos_prueba)
```


```{r}

#CONFIRMACIÓN DE QUE NO HAY NAN

sum(is.na(datos_entrenamiento))
sum(is.na(datos_prueba))
```


```{r}
#CONTEO DE VALORES DE ENTRENAMIENTO SMOKING (NO FUMADORES / FUMADORES)

summary(datos_entrenamiento$smoking)
```



```{r}

#BALANCEO DE DATOS DE ENTRENAMIENTO

# Contar el número de instancias para cada valor de 'smoking'
table(datos_entrenamiento$smoking)

# Realizar submuestreo
set.seed(2023)  
datos_entrenamiento_balanceados <- datos_entrenamiento %>%
  group_by(smoking) %>%
  sample_n(23543) #AQUÍ ES SEGÚN EL NÚMERO DE TRUE Y FALSE QUERRAMOS USAR.

# Verificar el nuevo conteo
table(datos_entrenamiento_balanceados$smoking)

print(datos_entrenamiento_balanceados)
```


```{r}
#MODELO DE MACHINE DECISION TREE CON DATOS BALANCEADOS

modelo_arbol <- rpart(smoking ~ ., data = datos_entrenamiento_balanceados, method = "class")

predicciones_arbol <- predict(modelo_arbol, datos_prueba,type = "class")
```


```{r}
#MATRIZ DE CONFUSIÓN DECISION TREE BALANCEADO

verdaderos <- datos_prueba$smoking  
predicciones <- predicciones_arbol

mc <- confusionMatrix(predicciones, verdaderos)

print(mc)
```


```{r}
#VISUALIZACIÓN DE DECISION TREE

library(rpart)
library(rpart.plot)

rpart.plot(modelo_arbol)
```

```{r}

#MODELO DE MACHINE DECISION TREE SIN BALANCEO DE DATOS

modelo_arbol <- rpart(smoking ~ ., data = datos_entrenamiento, method = "class")

predicciones_arbol <- predict(modelo_arbol, datos_prueba,type = "class")

```


```{r}
#MATRIZ DE CONFUSIÓN DECISION TREE SIN BALANCEO DE DATOS

verdaderos <- datos_prueba$smoking  
predicciones <- predicciones_arbol

mc <- confusionMatrix(predicciones, verdaderos)

print(mc)
```


```{r}
#VISUALIZACIÓN DE DECISION TREE SIN BALANCEO DE DATOS

library(rpart)
library(rpart.plot)

rpart.plot(modelo_arbol)

```

```{r}
#MODELO XGBOOST 1

# Conversión a matriz necesaria para el modelo
matriz = model.matrix(smoking ~ . -1, data = dataset_filtrado)

set.seed(2023)

trainIndex <-createDataPartition(dataset_filtrado$smoking, p = proporcion_entrenamiento,
                                 list = FALSE, times = 1)

# Matriz de entrenamiento, y de entrenamiento, matriz de prueba y y de prueba
matriz_train <- matriz[trainIndex,]

y_train = dataset_filtrado$smoking[trainIndex]

y_train_numeric <- as.numeric(as.factor(y_train)) - 1



matriz_test <- matriz[-trainIndex,]

y_test = dataset_filtrado$smoking[-trainIndex]

y_test_numeric <- as.numeric(as.factor(y_test)) - 1

# Aplicación del modelo
modelo_xgboost <- xgboost(data = matriz_train, max.depth = 8, eta = 1, nthread = 2,
                          label = y_train_numeric, nrounds = 100, objective = "binary:logistic",
                          eval.metric='error', verbose = 1)
```

```{r}
#MATRIZ DE CONFUSIÓN XGBOOST 1

# Convertir clasificaciones a factor (0, 1)
predicciones_xgboost <- predict(modelo_xgboost, matriz_test)

pred_xgboost <- as.numeric(predicciones_xgboost > 0.5)

# Convertir a factores
pred_xgboost <- as.factor(pred_xgboost)
y_test <- as.factor(y_test)

# Asegurar que ambos tengan los mismos niveles
levels(pred_xgboost) <- levels(y_test)

# Crear la matriz de confusión
mc_xgboost <- confusionMatrix(pred_xgboost, y_test)

# Imprimir la matriz de confusión
print(mc_xgboost)
```
```{r}
#IMPORTANCIA DE LAS VARIABLES EN XGBOOST
importance <- xgb.importance(feature_names = colnames(matriz_train), model = modelo_xgboost)
head(importance, n= 10)

xgb.plot.importance(importance_matrix = importance)

# VALIDACION CRUZADA XGBOOST 1

xgb.fit1 <- xgb.cv(
  data = matriz_train,
  label = y_train_numeric,
  nrounds = 100,
  eval.metric = 'error',
  max.depth = 8,
  eta = 1,
  nfold = 5,
  objective = "binary:logistic",
    verbose = 0
)

xgb.fit1$evaluation_log

ggplot(xgb.fit1$evaluation_log) + 
  geom_line(aes(iter, train_error_mean), color= "red") +
  geom_line(aes(iter, test_error_mean), color= "blue")
```

```{r}
#MEJORA EL MODELO XGBOOST1

xgb.fit <- xgb.cv(
  data = matriz_train,
  label = y_train_numeric,
  eval.metric = 'logloss',
  objective = "binary:logistic",
  nfold = 10,
  
  max.depth = 8,
  eta = 0.06,
  nthread= 5,
  subsample= 1,
  colsample_bytree= 0.5,
  lambda= 0.5,
  alpha= 0.5,
  min_child_weight= 3,
  nrounds = 125,
)

xgb.fit$evaluation_log

ggplot(xgb.fit$evaluation_log) + 
  geom_line(aes(iter, train_logloss_mean), color= "red") +
  geom_line(aes(iter, test_logloss_mean), color= "blue")
```
```{r}
#MODELO XGBOOST 2 SIN BALANCEO DE DATOS
xgb.2 <- xgboost(data = matriz_train,
                 max.depth = 8,
                 eta = 0.06,
                 nthread = 5,
                 label = y_train_numeric,
                 nrounds = 125,
                 objective = "binary:logistic",
                 colsample_bytree= 0.5,
                 lambda= 0.5,
                 alpha= 0.5,
                 min_child_weight= 3,
                 eval.metric='logloss',
                 verbose = 1)
```

```{r}
#MATRIZ DE CONFUSIÓN XGBOOST 2 SIN BALANCEO DE DATOS

# Convertir clasificaciones a factor (0, 1)
predicciones_xgb.2 <- predict(xgb.2, matriz_test)

pred_xgb.2 <- as.numeric(predicciones_xgb.2 > 0.5)

# Convertir a factores
pred_xgb.2 <- as.factor(pred_xgb.2)
y_test <- as.factor(y_test)

# Asegurar que ambos tengan los mismos niveles
levels(pred_xgb.2) <- levels(y_test)

# Crear la matriz de confusión
mc_xgb.2 <- confusionMatrix(pred_xgb.2, y_test)

# Imprimir la matriz de confusión
print(mc_xgb.2)
```

```{r}
#MODELO XGBOOST 2 CON DATOS BALANCEADOS

#DIVIDIR DATOS DE ENTRENAMIENTO Y DE PRUEBA

#BALANCEO DE DATOS DE ENTRENAMIENTO

# Matriz de entrenamiento, y de entrenamiento, matriz de prueba y y de prueba
matriz_train <- model.matrix(smoking ~ . -1, data = datos_entrenamiento_balanceados)

y_train = datos_entrenamiento_balanceados$smoking

y_train_numeric <- as.numeric(as.factor(y_train)) - 1



matriz_test <- model.matrix(smoking ~ . -1, data = datos_prueba)

y_test = datos_prueba$smoking

y_test_numeric <- as.numeric(as.factor(y_test)) - 1

# Aplicación del modelo

xgb.3 <- xgboost(data = matriz_train,
                 max.depth = 8,
                 eta = 0.06,
                 nthread = 5,
                 label = y_train_numeric,
                 nrounds = 125,
                 objective = "binary:logistic",
                 colsample_bytree= 0.5,
                 lambda= 0.5,
                 alpha= 0.5,
                 min_child_weight= 3,
                 eval.metric='logloss',
                 verbose = 1)
```

```{r}
#MATRIZ DE CONFUSIÓN XGBOOST 2 CON DATOS BALANCEADOS
# Convertir clasificaciones a factor (0, 1)
predicciones_xgb.3 <- predict(xgb.3, matriz_test)

pred_xgb.3 <- as.numeric(predicciones_xgb.3 > 0.5)

# Convertir a factores
pred_xgb.3 <- as.factor(pred_xgb.3)
y_test <- as.factor(y_test)

# Asegurar que ambos tengan los mismos niveles
levels(pred_xgb.3) <- levels(y_test)

# Crear la matriz de confusión
mc_xgb.3 <- confusionMatrix(pred_xgb.3, y_test)

# Imprimir la matriz de confusión
print(mc_xgb.3)
```


```{r}
#MODELO KNN SIN BALANCEO DE DATOS
modelo_knn <- train.kknn(smoking ~ ., data = datos_entrenamiento)
predicciones_knn <- predict(modelo_knn, datos_prueba)
```

```{r}
#MATRIZ DE CONFUSIÓN KNN SIN BALANCEO DE DATOS

verdaderos <-datos_prueba$smoking
predicciones <- predicciones_knn

mc <-confusionMatrix(predicciones, verdaderos)

print(mc)
```

```{r}
#MODELO KNN CON DATOS BALANCEADOS
modelo_knn_bal <- train.kknn(smoking ~ ., data = datos_entrenamiento_balanceados)#, kmax = 2)
predicciones_knn_bal <- predict(modelo_knn_bal, datos_prueba)
```

```{r}
#MATRIZ DE CONFUSIÓN KNN CON DATOS BALANCEADOS

verdaderos_knn_bal <-datos_prueba$smoking
predicciones_knn_bal <- predicciones_knn_bal

mc <-confusionMatrix(predicciones_knn_bal, verdaderos_knn_bal)

print(mc)
```


